name: Deploy Microservices to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}   # ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Connected to EC2"
            whoami
            hostname

            cd ~/QMA-Micro   # 👈 your new repo folder name

            echo "Fixing mvnw permissions..."
            find . -name "mvnw" -exec chmod +x {} \;
            
            echo "Cleaning old builds..."
            find . -name "target" -type d -exec rm -rf {} +
            
            echo "Building and starting services..."
            
            # ServiceRegistry
            cd ServiceRegistry
            ./mvnw clean package -DskipTests
            nohup java -jar target/*.jar --server.port=8761 > ~/logs/service-registry.log 2>&1 &
            cd ..
            sleep 10
            
            # QuantityMeasurementApp
            cd QuantityMeasurementApp
            ./mvnw clean package -DskipTests
            nohup java -jar target/*.jar --server.port=8081 > ~/logs/quantity-app.log 2>&1 &
            cd ..
            sleep 5
            
            # ApiGateway
            cd ApiGateway
            ./mvnw clean package -DskipTests
            nohup java -jar target/*.jar --server.port=8080 > ~/logs/api-gateway.log 2>&1 &
            cd ..
